services:
  clamav-hashbuilder:
    build: .
    container_name: clamav-hashbuilder
    volumes:
      - ./hashsets:/opt/hashsets
    environment:
      - HASHBUILDER_FREQUENCY=24
    restart: unless-stopped
